from typing import Protocol, Any, Annotated
from pydantic import Field

class DatabaseConnector(Protocol):
    async def open(self, retry: Any) -> Annotated[Any, Field(description="open connection and return the client")]: ...
    async def close(self) -> Annotated[None, Field(description="close connection")]: ...
    async def health_check_loop(self, config: Any) -> Annotated[None, Field(description="health check loop")]: ...
    def is_healthy(self) -> Annotated[bool, Field(description="T if healthy else F")]: ...
    def is_connected(self) -> Annotated[bool, Field(description="T if connected else F")]: ...
    def get_client(self) -> Annotated[Any, Field(description="Client object")]: ...
    def set_url(self, url: str) -> Annotated[None, Field(description="Client object")]: ...