name: aeroflow-test

services:
  postgres-test:
    image: postgres:16
    container_name: aeroflow-postgres-test
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: aeroflow_test
      POSTGRES_HOST_AUTH_METHOD: trust
    tmpfs:
      - /var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
