"""initial

Revision ID: bbf27f18c27d
Revises: 
Create Date: 2026-06-03 09:26:50.405093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbf27f18c27d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DriftEvents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('env_pair', sa.Text(), nullable=False),
    sa.Column('drift_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_drift_events_inserted_at_desc', 'DriftEvents', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_drift_events_resolved', 'DriftEvents', ['resolved', 'detected_at'], unique=False)
    op.create_table('EnvironmentConfigs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment', 'key', 'version', name='uq_env_configs')
    )
    op.create_index('idx_env_configs_env', 'EnvironmentConfigs', ['environment', 'is_active'], unique=False)
    op.create_index('idx_env_configs_inserted_at_desc', 'EnvironmentConfigs', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_table('KBEntityLookup',
    sa.Column('lookup_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(length=512), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('lookup_id')
    )
    op.create_index('idx_kbentitylookup_alias', 'KBEntityLookup', ['alias_name'], unique=False, postgresql_using='hash')
    op.create_index('idx_kbentitylookup_inserted_at_desc', 'KBEntityLookup', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBEntityLookup_canonical_name'), 'KBEntityLookup', ['canonical_name'], unique=False)
    op.create_index(op.f('ix_KBEntityLookup_created_at'), 'KBEntityLookup', ['created_at'], unique=False)
    op.create_table('KBModel',
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_index('idx_kbmodel_inserted_at_desc', 'KBModel', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBModel_created_at'), 'KBModel', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBModel_task_type'), 'KBModel', ['task_type'], unique=False)
    op.create_table('KBWarehouse',
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id')
    )
    op.create_index('idx_kbwarehouse_inserted_at_desc', 'KBWarehouse', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBWarehouse_created_at'), 'KBWarehouse', ['created_at'], unique=False)
    op.create_table('LLMProviders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llmproviders_inserted_at_desc', 'LLMProviders', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_llmproviders_type_is_default', 'LLMProviders', ['type', 'is_default'], unique=False, postgresql_where=sa.text('is_default = true'))
    op.create_table('Pipelines',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('pipeline_name', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.Text(), nullable=False),
    sa.Column('commit_sha', sa.Text(), nullable=True),
    sa.Column('branch', sa.Text(), nullable=True),
    sa.Column('package_version', sa.Text(), nullable=True),
    sa.Column('target_env', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.SmallInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipelines_inserted_at_desc', 'Pipelines', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_pipelines_status', 'Pipelines', ['status', 'created_at'], unique=False)
    op.create_table('Plans',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_envs', sa.SmallInteger(), nullable=True),
    sa.Column('max_secrets', sa.Integer(), nullable=True),
    sa.Column('max_deploy_daily', sa.Integer(), nullable=True),
    sa.Column('max_api_keys', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('RolePermissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.String(length=50), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'resource', 'action', name='uq_role_permissions')
    )
    op.create_index('idx_role_permissions_inserted_at_desc', 'RolePermissions', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_role_permissions_role', 'RolePermissions', ['role_id'], unique=False)
    op.create_table('Guardrails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('guardrail_model_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guardrail_model_id'], ['LLMProviders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guardrails_inserted_at_desc', 'Guardrails', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_table('KBModelVersion',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('added_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['KBModel.model_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_kbmodelversion_inserted_at_desc', 'KBModelVersion', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbmodelversion_model_version', 'KBModelVersion', ['model_id', 'version_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index(op.f('ix_KBModelVersion_created_at'), 'KBModelVersion', ['created_at'], unique=False)
    op.create_table('KBWarehouseConfig',
    sa.Column('config_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['KBWarehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index('idx_kbwarehouseconfig_inserted_at_desc', 'KBWarehouseConfig', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbwarehouseconfig_wh_active', 'KBWarehouseConfig', ['warehouse_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_kbwarehouseconfig_wh_version', 'KBWarehouseConfig', ['warehouse_id', 'version_number'], unique=False)
    op.create_index(op.f('ix_KBWarehouseConfig_created_at'), 'KBWarehouseConfig', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBWarehouseConfig_warehouse_id'), 'KBWarehouseConfig', ['warehouse_id'], unique=False)
    op.create_table('PipelineSteps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Text(), nullable=False),
    sa.Column('step_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pipeline_steps_inserted_at_desc', 'PipelineSteps', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_pipeline_steps_pipeline', 'PipelineSteps', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_PipelineSteps_pipeline_id'), 'PipelineSteps', ['pipeline_id'], unique=False)
    op.create_table('ReleasePackages',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('pipeline_id', sa.Text(), nullable=True),
    sa.Column('artifact_paths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_score', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('environment_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scan_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('promoted_to_s3_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_release_packages_inserted_at_desc', 'ReleasePackages', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_release_packages_status', 'ReleasePackages', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_ReleasePackages_pipeline_id'), 'ReleasePackages', ['pipeline_id'], unique=False)
    op.create_table('RollbackOperations',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('pipeline_id', sa.Text(), nullable=True),
    sa.Column('from_version', sa.Text(), nullable=False),
    sa.Column('to_version', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('current_step', sa.SmallInteger(), nullable=False),
    sa.Column('steps_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rollback_ops_env', 'RollbackOperations', ['environment', 'started_at'], unique=False)
    op.create_index('idx_rollback_ops_inserted_at_desc', 'RollbackOperations', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_RollbackOperations_pipeline_id'), 'RollbackOperations', ['pipeline_id'], unique=False)
    op.create_table('Tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan_id', sa.SmallInteger(), nullable=True),
    sa.Column('data_residency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['Plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_tenants_inserted_at_desc', 'Tenants', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_tenants_slug', 'Tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_Tenants_created_at'), 'Tenants', ['created_at'], unique=False)
    op.create_index(op.f('ix_Tenants_plan_id'), 'Tenants', ['plan_id'], unique=False)
    op.create_table('APIKeys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_from', sa.UUID(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rotated_from'], ['APIKeys.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    sa.UniqueConstraint('tenant_id', 'key_prefix', name='uq_api_keys_tenant_prefix')
    )
    op.create_index('idx_api_keys_inserted_at_desc', 'APIKeys', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_api_keys_key_hash', 'APIKeys', ['key_hash'], unique=False)
    op.create_index('idx_api_keys_tenant', 'APIKeys', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_APIKeys_tenant_id'), 'APIKeys', ['tenant_id'], unique=False)
    op.create_table('Agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('published_version_id', sa.UUID(), nullable=True),
    sa.Column('draft_version_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_version_id'], ['AgentVersions.id'], name='fk_agents_draft_version', use_alter=True),
    sa.ForeignKeyConstraint(['published_version_id'], ['AgentVersions.id'], name='fk_agents_published_version', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agents_inserted_at_desc', 'Agents', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_agents_tenant', 'Agents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_Agents_tenant_id'), 'Agents', ['tenant_id'], unique=False)
    op.create_table('AuditLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_inserted_at_desc', 'AuditLogs', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_audit_logs_source_event', 'AuditLogs', ['source_event_id'], unique=False, postgresql_where=sa.text('source_event_id IS NOT NULL'))
    op.create_index('idx_audit_logs_tenant', 'AuditLogs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_AuditLogs_created_at'), 'AuditLogs', ['created_at'], unique=False)
    op.create_table('IPAllowlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cidr', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ip_allowlists_inserted_at_desc', 'IPAllowlists', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_ip_allowlists_tenant', 'IPAllowlists', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_IPAllowlists_tenant_id'), 'IPAllowlists', ['tenant_id'], unique=False)
    op.create_table('KBConflictBatch',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('batch_title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index('idx_kbconflictbatch_inserted_at_desc', 'KBConflictBatch', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBConflictBatch_created_at'), 'KBConflictBatch', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBConflictBatch_tenant_id'), 'KBConflictBatch', ['tenant_id'], unique=False)
    op.create_table('KBConnections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbconnections_inserted_at_desc', 'KBConnections', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbconnections_tenant', 'KBConnections', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_KBConnections_tenant_id'), 'KBConnections', ['tenant_id'], unique=False)
    op.create_table('KBData',
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_tier', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=True),
    sa.Column('added_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['RolePermissions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('data_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_kbdata_inserted_at_desc', 'KBData', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbdata_tenant_role', 'KBData', ['tenant_id', 'role_id'], unique=False)
    op.create_index('idx_kbdata_tenant_source', 'KBData', ['tenant_id', 'source_type'], unique=False)
    op.create_index('idx_kbdata_tenant_tier', 'KBData', ['tenant_id', 'current_tier'], unique=False)
    op.create_index(op.f('ix_KBData_created_at'), 'KBData', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBData_tenant_id'), 'KBData', ['tenant_id'], unique=False)
    op.create_table('KBExtractionPolicy',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=64), nullable=False),
    sa.Column('custom_override', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index('idx_kbextractionpolicy_inserted_at_desc', 'KBExtractionPolicy', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbextractionpolicy_tenant_lang', 'KBExtractionPolicy', ['tenant_id', 'language'], unique=False)
    op.create_index(op.f('ix_KBExtractionPolicy_created_at'), 'KBExtractionPolicy', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBExtractionPolicy_tenant_id'), 'KBExtractionPolicy', ['tenant_id'], unique=False)
    op.create_table('KBFilterPolicy',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(length=255), nullable=False),
    sa.Column('configformat', sa.String(length=64), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index('idx_kbfilterpolicy_inserted_at_desc', 'KBFilterPolicy', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbfilterpolicy_tenant_lang', 'KBFilterPolicy', ['tenant_id', 'language'], unique=False)
    op.create_index(op.f('ix_KBFilterPolicy_created_at'), 'KBFilterPolicy', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBFilterPolicy_tenant_id'), 'KBFilterPolicy', ['tenant_id'], unique=False)
    op.create_table('KBNeo4jConnection',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_connected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_node', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_edge', sa.Integer(), server_default='0', nullable=False),
    sa.Column('embedding_model_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['KBModel.model_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index('idx_kbneo4jconn_tenant_connected', 'KBNeo4jConnection', ['tenant_id'], unique=False, postgresql_where=sa.text('is_connected = true'))
    op.create_index('idx_kbneo4jconnection_inserted_at_desc', 'KBNeo4jConnection', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBNeo4jConnection_created_at'), 'KBNeo4jConnection', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBNeo4jConnection_tenant_id'), 'KBNeo4jConnection', ['tenant_id'], unique=False)
    op.create_table('KBPublishAPI',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('endpoint_url', sa.String(length=1024), nullable=False),
    sa.Column('http_method', sa.String(length=8), nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kbpublishapi_inserted_at_desc', 'KBPublishAPI', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbpublishapi_tenant_published', 'KBPublishAPI', ['tenant_id'], unique=False, postgresql_where=sa.text('is_published = true'))
    op.create_index(op.f('ix_KBPublishAPI_created_at'), 'KBPublishAPI', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBPublishAPI_tenant_id'), 'KBPublishAPI', ['tenant_id'], unique=False)
    op.create_table('KBQdrantConnection',
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_collection', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('connection_id')
    )
    op.create_index('idx_kbqdrantconn_tenant_active', 'KBQdrantConnection', ['tenant_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_kbqdrantconnection_inserted_at_desc', 'KBQdrantConnection', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBQdrantConnection_created_at'), 'KBQdrantConnection', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBQdrantConnection_tenant_id'), 'KBQdrantConnection', ['tenant_id'], unique=False)
    op.create_table('KeycloakRealmConfigs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('realm_name', sa.String(length=100), nullable=False),
    sa.Column('keycloak_base_url', sa.Text(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret_ref', sa.Text(), nullable=False),
    sa.Column('jwks_url', sa.Text(), nullable=False),
    sa.Column('token_endpoint', sa.Text(), nullable=False),
    sa.Column('token_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id'),
    sa.UniqueConstraint('realm_name')
    )
    op.create_index('idx_keycloakrealmconfigs_inserted_at_desc', 'KeycloakRealmConfigs', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_table('MCP',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('endpoint_url', sa.Text(), nullable=False),
    sa.Column('api_key_ref', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mcp_inserted_at_desc', 'MCP', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_mcp_tenant', 'MCP', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_MCP_tenant_id'), 'MCP', ['tenant_id'], unique=False)
    op.create_table('PIIAccessLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('accessor_id', sa.String(length=255), nullable=True),
    sa.Column('accessor_type', sa.String(length=20), nullable=False),
    sa.Column('data_subject', sa.String(length=255), nullable=True),
    sa.Column('field_accessed', sa.String(length=100), nullable=True),
    sa.Column('access_reason', sa.Text(), nullable=True),
    sa.Column('scrubbed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pii_access_logs_inserted_at_desc', 'PIIAccessLogs', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_pii_access_logs_tenant', 'PIIAccessLogs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_PIIAccessLogs_created_at'), 'PIIAccessLogs', ['created_at'], unique=False)
    op.create_table('ReleaseApprovals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.Text(), nullable=False),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['ReleasePackages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'environment', 'approved_by', name='uq_release_approvals')
    )
    op.create_index('idx_release_approvals_inserted_at_desc', 'ReleaseApprovals', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_release_approvals_package', 'ReleaseApprovals', ['package_id'], unique=False)
    op.create_index(op.f('ix_ReleaseApprovals_package_id'), 'ReleaseApprovals', ['package_id'], unique=False)
    op.create_table('ReleaseHistory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pipeline_id', sa.Text(), nullable=False),
    sa.Column('package_id', sa.Text(), nullable=True),
    sa.Column('environment', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['ReleasePackages.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['Pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_release_history_env', 'ReleaseHistory', ['environment', 'deployed_at'], unique=False)
    op.create_index('idx_release_history_inserted_at_desc', 'ReleaseHistory', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_release_history_pipeline', 'ReleaseHistory', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_ReleaseHistory_deployed_at'), 'ReleaseHistory', ['deployed_at'], unique=False)
    op.create_index(op.f('ix_ReleaseHistory_pipeline_id'), 'ReleaseHistory', ['pipeline_id'], unique=False)
    op.create_table('SecretsVault',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=True),
    sa.Column('realm', sa.String(length=100), nullable=True),
    sa.Column('openbao_path', sa.Text(), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('rotation_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key_name', 'version', name='uq_secrets_vault_tenant_name')
    )
    op.create_index('idx_secrets_vault_inserted_at_desc', 'SecretsVault', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_SecretsVault_tenant_id'), 'SecretsVault', ['tenant_id'], unique=False)
    op.create_table('SystemPrompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_systemprompts_inserted_at_desc', 'SystemPrompts', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_systemprompts_tenant', 'SystemPrompts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_SystemPrompts_tenant_id'), 'SystemPrompts', ['tenant_id'], unique=False)
    op.create_table('Tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tools_inserted_at_desc', 'Tools', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_tools_tenant', 'Tools', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_Tools_tenant_id'), 'Tools', ['tenant_id'], unique=False)
    op.create_table('Webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_ref', sa.String(length=255), nullable=True),
    sa.Column('events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failure_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_webhooks_inserted_at_desc', 'Webhooks', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_webhooks_tenant', 'Webhooks', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_Webhooks_tenant_id'), 'Webhooks', ['tenant_id'], unique=False)
    op.create_table('AgentMemories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('user_ref', sa.String(length=255), nullable=True),
    sa.Column('memory_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding_ref', sa.String(length=255), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['Agents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agentmemories_agent_scope', 'AgentMemories', ['agent_id', 'scope'], unique=False)
    op.create_index('idx_agentmemories_agent_user_ref', 'AgentMemories', ['agent_id', 'user_ref'], unique=False)
    op.create_index('idx_agentmemories_deleted_at', 'AgentMemories', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('idx_agentmemories_inserted_at_desc', 'AgentMemories', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_agentmemories_tenant', 'AgentMemories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_AgentMemories_agent_id'), 'AgentMemories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_AgentMemories_tenant_id'), 'AgentMemories', ['tenant_id'], unique=False)
    op.create_table('KBConflict',
    sa.Column('conflict_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('conflict_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('detailed_explanation', sa.Text(), nullable=True),
    sa.Column('existing_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('incoming_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolution_instruction', sa.Text(), nullable=True),
    sa.Column('resolution_method', sa.String(length=20), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['KBConflictBatch.batch_id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    op.create_index('idx_kbconflict_inserted_at_desc', 'KBConflict', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbconflict_tenant_status_severity', 'KBConflict', ['tenant_id', 'status', 'severity'], unique=False)
    op.create_index(op.f('ix_KBConflict_batch_id'), 'KBConflict', ['batch_id'], unique=False)
    op.create_index(op.f('ix_KBConflict_created_at'), 'KBConflict', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBConflict_tenant_id'), 'KBConflict', ['tenant_id'], unique=False)
    op.create_table('KBLifecycleHistory',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('data_id', sa.UUID(), nullable=False),
    sa.Column('to_tier', sa.String(length=16), nullable=False),
    sa.Column('from_tier', sa.String(length=16), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('transitioned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['data_id'], ['KBData.data_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('idx_kblifecyclehistory_inserted_at_desc', 'KBLifecycleHistory', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBLifecycleHistory_created_at'), 'KBLifecycleHistory', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBLifecycleHistory_data_id'), 'KBLifecycleHistory', ['data_id'], unique=False)
    op.create_table('KBNeo4jNode',
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=512), nullable=False),
    sa.Column('node_description', sa.Text(), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['KBNeo4jConnection.connection_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('idx_kbneo4jnode_inserted_at_desc', 'KBNeo4jNode', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBNeo4jNode_connection_id'), 'KBNeo4jNode', ['connection_id'], unique=False)
    op.create_index(op.f('ix_KBNeo4jNode_created_at'), 'KBNeo4jNode', ['created_at'], unique=False)
    op.create_table('KBQdrantCollection',
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('similarity_metric', sa.String(length=16), nullable=False),
    sa.Column('points_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=True),
    sa.Column('embedding_model_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['KBQdrantConnection.connection_id'], ),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['KBModel.model_id'], ),
    sa.PrimaryKeyConstraint('collection_id')
    )
    op.create_index('idx_kbqdrantcollection_inserted_at_desc', 'KBQdrantCollection', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBQdrantCollection_connection_id'), 'KBQdrantCollection', ['connection_id'], unique=False)
    op.create_index(op.f('ix_KBQdrantCollection_created_at'), 'KBQdrantCollection', ['created_at'], unique=False)
    op.create_table('KBTable',
    sa.Column('table_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['KBData.data_id'], ),
    sa.PrimaryKeyConstraint('table_id')
    )
    op.create_index('idx_kbtable_inserted_at_desc', 'KBTable', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBTable_created_at'), 'KBTable', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBTable_owner_id'), 'KBTable', ['owner_id'], unique=False)
    op.create_index(op.f('ix_KBTable_table_name'), 'KBTable', ['table_name'], unique=False)
    op.create_table('KBTextBlock',
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('block_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['KBData.data_id'], ),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_index('idx_kbtextblock_inserted_at_desc', 'KBTextBlock', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_kbtextblock_owner_block', 'KBTextBlock', ['owner_id', 'block_id'], unique=False)
    op.create_index(op.f('ix_KBTextBlock_created_at'), 'KBTextBlock', ['created_at'], unique=False)
    op.create_index(op.f('ix_KBTextBlock_owner_id'), 'KBTextBlock', ['owner_id'], unique=False)
    op.create_table('KeyRotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('secret_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('old_version', sa.SmallInteger(), nullable=True),
    sa.Column('new_version', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('rotated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['secret_id'], ['SecretsVault.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_key_rotations_inserted_at_desc', 'KeyRotations', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_key_rotations_secret', 'KeyRotations', ['secret_id'], unique=False)
    op.create_index(op.f('ix_KeyRotations_secret_id'), 'KeyRotations', ['secret_id'], unique=False)
    op.create_table('MemoryPolicy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=20), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['Agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memorypolicy_agent', 'MemoryPolicy', ['agent_id'], unique=False)
    op.create_index('idx_memorypolicy_inserted_at_desc', 'MemoryPolicy', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_MemoryPolicy_agent_id'), 'MemoryPolicy', ['agent_id'], unique=False)
    op.create_table('Workflows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['Agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflows_agent', 'Workflows', ['agent_id'], unique=False)
    op.create_index('idx_workflows_inserted_at_desc', 'Workflows', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_Workflows_agent_id'), 'Workflows', ['agent_id'], unique=False)
    op.create_table('KBNeo4jRelationship',
    sa.Column('from_node', sa.UUID(), nullable=False),
    sa.Column('to_node', sa.UUID(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['from_node'], ['KBNeo4jNode.node_id'], ),
    sa.ForeignKeyConstraint(['to_node'], ['KBNeo4jNode.node_id'], ),
    sa.PrimaryKeyConstraint('from_node', 'to_node')
    )
    op.create_index('idx_kbneo4jrelationship_inserted_at_desc', 'KBNeo4jRelationship', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBNeo4jRelationship_created_at'), 'KBNeo4jRelationship', ['created_at'], unique=False)
    op.create_table('KBTextBlockVersion',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('table_involved', sa.Boolean(), nullable=True),
    sa.Column('embedding_model_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['KBTextBlock.block_id'], ),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['KBModel.model_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_kbtextblockversion_block_version', 'KBTextBlockVersion', ['block_id', 'version_number'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_kbtextblockversion_inserted_at_desc', 'KBTextBlockVersion', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBTextBlockVersion_block_id'), 'KBTextBlockVersion', ['block_id'], unique=False)
    op.create_index(op.f('ix_KBTextBlockVersion_created_at'), 'KBTextBlockVersion', ['created_at'], unique=False)
    op.create_table('WorkflowVersions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('changelog', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['Workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_workflow_versions_workflow_version')
    )
    op.create_index('idx_workflowversions_inserted_at_desc', 'WorkflowVersions', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_workflowversions_workflow_status', 'WorkflowVersions', ['workflow_id', 'status'], unique=False)
    op.create_index(op.f('ix_WorkflowVersions_workflow_id'), 'WorkflowVersions', ['workflow_id'], unique=False)
    op.create_table('AgentVersions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('workflow_version_id', sa.UUID(), nullable=True),
    sa.Column('reasoner_model_id', sa.UUID(), nullable=True),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_prompt_id', sa.UUID(), nullable=True),
    sa.Column('guardrail_id', sa.UUID(), nullable=True),
    sa.Column('memory_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('retrieval_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changelog', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['Agents.id'], ),
    sa.ForeignKeyConstraint(['guardrail_id'], ['Guardrails.id'], ),
    sa.ForeignKeyConstraint(['reasoner_model_id'], ['LLMProviders.id'], ),
    sa.ForeignKeyConstraint(['system_prompt_id'], ['SystemPrompts.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['WorkflowVersions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_versions_agent_version')
    )
    op.create_index('idx_agentversions_agent_status', 'AgentVersions', ['agent_id', 'status'], unique=False)
    op.create_index('idx_agentversions_inserted_at_desc', 'AgentVersions', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_AgentVersions_agent_id'), 'AgentVersions', ['agent_id'], unique=False)
    op.create_table('KBTextTable',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['KBTextBlockVersion.version_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index('idx_kbtexttable_inserted_at_desc', 'KBTextTable', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_KBTextTable_created_at'), 'KBTextTable', ['created_at'], unique=False)
    op.create_table('AgentKB',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('kb_connection_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_connection_id'], ['KBConnections.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['AgentVersions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'kb_connection_id')
    )
    op.create_table('AgentMCP',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('mcp_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mcp_id'], ['MCP.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['AgentVersions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'mcp_id')
    )
    op.create_table('AgentTools',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('tool_id', sa.UUID(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['Tools.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['AgentVersions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'tool_id')
    )
    op.create_table('Conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('agent_version_id', sa.UUID(), nullable=False),
    sa.Column('user_ref', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['AgentVersions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['Tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_agent_version', 'Conversations', ['agent_version_id'], unique=False)
    op.create_index('idx_conversations_inserted_at_desc', 'Conversations', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index('idx_conversations_tenant', 'Conversations', ['tenant_id'], unique=False)
    op.create_index('idx_conversations_tenant_user_ref', 'Conversations', ['tenant_id', 'user_ref'], unique=False)
    op.create_index(op.f('ix_Conversations_agent_version_id'), 'Conversations', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_Conversations_tenant_id'), 'Conversations', ['tenant_id'], unique=False)
    op.create_table('Messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['Conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created', 'Messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_inserted_at_desc', 'Messages', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_Messages_conversation_id'), 'Messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_Messages_created_at'), 'Messages', ['created_at'], unique=False)
    op.create_table('AgentTraces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('trace_index', sa.SmallInteger(), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['Messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'trace_index', name='uq_agent_traces_message_index')
    )
    op.create_index('idx_agenttraces_inserted_at_desc', 'AgentTraces', [sa.literal_column('inserted_at DESC')], unique=False)
    op.create_index(op.f('ix_AgentTraces_message_id'), 'AgentTraces', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_AgentTraces_message_id'), table_name='AgentTraces')
    op.drop_index('idx_agenttraces_inserted_at_desc', table_name='AgentTraces')
    op.drop_table('AgentTraces')
    op.drop_index(op.f('ix_Messages_created_at'), table_name='Messages')
    op.drop_index(op.f('ix_Messages_conversation_id'), table_name='Messages')
    op.drop_index('idx_messages_inserted_at_desc', table_name='Messages')
    op.drop_index('idx_messages_conversation_created', table_name='Messages')
    op.drop_table('Messages')
    op.drop_index(op.f('ix_Conversations_tenant_id'), table_name='Conversations')
    op.drop_index(op.f('ix_Conversations_agent_version_id'), table_name='Conversations')
    op.drop_index('idx_conversations_tenant_user_ref', table_name='Conversations')
    op.drop_index('idx_conversations_tenant', table_name='Conversations')
    op.drop_index('idx_conversations_inserted_at_desc', table_name='Conversations')
    op.drop_index('idx_conversations_agent_version', table_name='Conversations')
    op.drop_table('Conversations')
    op.drop_table('AgentTools')
    op.drop_table('AgentMCP')
    op.drop_table('AgentKB')
    op.drop_index(op.f('ix_KBTextTable_created_at'), table_name='KBTextTable')
    op.drop_index('idx_kbtexttable_inserted_at_desc', table_name='KBTextTable')
    op.drop_table('KBTextTable')
    op.drop_index(op.f('ix_AgentVersions_agent_id'), table_name='AgentVersions')
    op.drop_index('idx_agentversions_inserted_at_desc', table_name='AgentVersions')
    op.drop_index('idx_agentversions_agent_status', table_name='AgentVersions')
    op.drop_table('AgentVersions')
    op.drop_index(op.f('ix_WorkflowVersions_workflow_id'), table_name='WorkflowVersions')
    op.drop_index('idx_workflowversions_workflow_status', table_name='WorkflowVersions')
    op.drop_index('idx_workflowversions_inserted_at_desc', table_name='WorkflowVersions')
    op.drop_table('WorkflowVersions')
    op.drop_index(op.f('ix_KBTextBlockVersion_created_at'), table_name='KBTextBlockVersion')
    op.drop_index(op.f('ix_KBTextBlockVersion_block_id'), table_name='KBTextBlockVersion')
    op.drop_index('idx_kbtextblockversion_inserted_at_desc', table_name='KBTextBlockVersion')
    op.drop_index('idx_kbtextblockversion_block_version', table_name='KBTextBlockVersion', postgresql_where=sa.text('is_active = true'))
    op.drop_table('KBTextBlockVersion')
    op.drop_index(op.f('ix_KBNeo4jRelationship_created_at'), table_name='KBNeo4jRelationship')
    op.drop_index('idx_kbneo4jrelationship_inserted_at_desc', table_name='KBNeo4jRelationship')
    op.drop_table('KBNeo4jRelationship')
    op.drop_index(op.f('ix_Workflows_agent_id'), table_name='Workflows')
    op.drop_index('idx_workflows_inserted_at_desc', table_name='Workflows')
    op.drop_index('idx_workflows_agent', table_name='Workflows')
    op.drop_table('Workflows')
    op.drop_index(op.f('ix_MemoryPolicy_agent_id'), table_name='MemoryPolicy')
    op.drop_index('idx_memorypolicy_inserted_at_desc', table_name='MemoryPolicy')
    op.drop_index('idx_memorypolicy_agent', table_name='MemoryPolicy')
    op.drop_table('MemoryPolicy')
    op.drop_index(op.f('ix_KeyRotations_secret_id'), table_name='KeyRotations')
    op.drop_index('idx_key_rotations_secret', table_name='KeyRotations')
    op.drop_index('idx_key_rotations_inserted_at_desc', table_name='KeyRotations')
    op.drop_table('KeyRotations')
    op.drop_index(op.f('ix_KBTextBlock_owner_id'), table_name='KBTextBlock')
    op.drop_index(op.f('ix_KBTextBlock_created_at'), table_name='KBTextBlock')
    op.drop_index('idx_kbtextblock_owner_block', table_name='KBTextBlock')
    op.drop_index('idx_kbtextblock_inserted_at_desc', table_name='KBTextBlock')
    op.drop_table('KBTextBlock')
    op.drop_index(op.f('ix_KBTable_table_name'), table_name='KBTable')
    op.drop_index(op.f('ix_KBTable_owner_id'), table_name='KBTable')
    op.drop_index(op.f('ix_KBTable_created_at'), table_name='KBTable')
    op.drop_index('idx_kbtable_inserted_at_desc', table_name='KBTable')
    op.drop_table('KBTable')
    op.drop_index(op.f('ix_KBQdrantCollection_created_at'), table_name='KBQdrantCollection')
    op.drop_index(op.f('ix_KBQdrantCollection_connection_id'), table_name='KBQdrantCollection')
    op.drop_index('idx_kbqdrantcollection_inserted_at_desc', table_name='KBQdrantCollection')
    op.drop_table('KBQdrantCollection')
    op.drop_index(op.f('ix_KBNeo4jNode_created_at'), table_name='KBNeo4jNode')
    op.drop_index(op.f('ix_KBNeo4jNode_connection_id'), table_name='KBNeo4jNode')
    op.drop_index('idx_kbneo4jnode_inserted_at_desc', table_name='KBNeo4jNode')
    op.drop_table('KBNeo4jNode')
    op.drop_index(op.f('ix_KBLifecycleHistory_data_id'), table_name='KBLifecycleHistory')
    op.drop_index(op.f('ix_KBLifecycleHistory_created_at'), table_name='KBLifecycleHistory')
    op.drop_index('idx_kblifecyclehistory_inserted_at_desc', table_name='KBLifecycleHistory')
    op.drop_table('KBLifecycleHistory')
    op.drop_index(op.f('ix_KBConflict_tenant_id'), table_name='KBConflict')
    op.drop_index(op.f('ix_KBConflict_created_at'), table_name='KBConflict')
    op.drop_index(op.f('ix_KBConflict_batch_id'), table_name='KBConflict')
    op.drop_index('idx_kbconflict_tenant_status_severity', table_name='KBConflict')
    op.drop_index('idx_kbconflict_inserted_at_desc', table_name='KBConflict')
    op.drop_table('KBConflict')
    op.drop_index(op.f('ix_AgentMemories_tenant_id'), table_name='AgentMemories')
    op.drop_index(op.f('ix_AgentMemories_agent_id'), table_name='AgentMemories')
    op.drop_index('idx_agentmemories_tenant', table_name='AgentMemories')
    op.drop_index('idx_agentmemories_inserted_at_desc', table_name='AgentMemories')
    op.drop_index('idx_agentmemories_deleted_at', table_name='AgentMemories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_agentmemories_agent_user_ref', table_name='AgentMemories')
    op.drop_index('idx_agentmemories_agent_scope', table_name='AgentMemories')
    op.drop_table('AgentMemories')
    op.drop_index(op.f('ix_Webhooks_tenant_id'), table_name='Webhooks')
    op.drop_index('idx_webhooks_tenant', table_name='Webhooks')
    op.drop_index('idx_webhooks_inserted_at_desc', table_name='Webhooks')
    op.drop_table('Webhooks')
    op.drop_index(op.f('ix_Tools_tenant_id'), table_name='Tools')
    op.drop_index('idx_tools_tenant', table_name='Tools')
    op.drop_index('idx_tools_inserted_at_desc', table_name='Tools')
    op.drop_table('Tools')
    op.drop_index(op.f('ix_SystemPrompts_tenant_id'), table_name='SystemPrompts')
    op.drop_index('idx_systemprompts_tenant', table_name='SystemPrompts')
    op.drop_index('idx_systemprompts_inserted_at_desc', table_name='SystemPrompts')
    op.drop_table('SystemPrompts')
    op.drop_index(op.f('ix_SecretsVault_tenant_id'), table_name='SecretsVault')
    op.drop_index('idx_secrets_vault_inserted_at_desc', table_name='SecretsVault')
    op.drop_table('SecretsVault')
    op.drop_index(op.f('ix_ReleaseHistory_pipeline_id'), table_name='ReleaseHistory')
    op.drop_index(op.f('ix_ReleaseHistory_deployed_at'), table_name='ReleaseHistory')
    op.drop_index('idx_release_history_pipeline', table_name='ReleaseHistory')
    op.drop_index('idx_release_history_inserted_at_desc', table_name='ReleaseHistory')
    op.drop_index('idx_release_history_env', table_name='ReleaseHistory')
    op.drop_table('ReleaseHistory')
    op.drop_index(op.f('ix_ReleaseApprovals_package_id'), table_name='ReleaseApprovals')
    op.drop_index('idx_release_approvals_package', table_name='ReleaseApprovals')
    op.drop_index('idx_release_approvals_inserted_at_desc', table_name='ReleaseApprovals')
    op.drop_table('ReleaseApprovals')
    op.drop_index(op.f('ix_PIIAccessLogs_created_at'), table_name='PIIAccessLogs')
    op.drop_index('idx_pii_access_logs_tenant', table_name='PIIAccessLogs')
    op.drop_index('idx_pii_access_logs_inserted_at_desc', table_name='PIIAccessLogs')
    op.drop_table('PIIAccessLogs')
    op.drop_index(op.f('ix_MCP_tenant_id'), table_name='MCP')
    op.drop_index('idx_mcp_tenant', table_name='MCP')
    op.drop_index('idx_mcp_inserted_at_desc', table_name='MCP')
    op.drop_table('MCP')
    op.drop_index('idx_keycloakrealmconfigs_inserted_at_desc', table_name='KeycloakRealmConfigs')
    op.drop_table('KeycloakRealmConfigs')
    op.drop_index(op.f('ix_KBQdrantConnection_tenant_id'), table_name='KBQdrantConnection')
    op.drop_index(op.f('ix_KBQdrantConnection_created_at'), table_name='KBQdrantConnection')
    op.drop_index('idx_kbqdrantconnection_inserted_at_desc', table_name='KBQdrantConnection')
    op.drop_index('idx_kbqdrantconn_tenant_active', table_name='KBQdrantConnection', postgresql_where=sa.text('is_active = true'))
    op.drop_table('KBQdrantConnection')
    op.drop_index(op.f('ix_KBPublishAPI_tenant_id'), table_name='KBPublishAPI')
    op.drop_index(op.f('ix_KBPublishAPI_created_at'), table_name='KBPublishAPI')
    op.drop_index('idx_kbpublishapi_tenant_published', table_name='KBPublishAPI', postgresql_where=sa.text('is_published = true'))
    op.drop_index('idx_kbpublishapi_inserted_at_desc', table_name='KBPublishAPI')
    op.drop_table('KBPublishAPI')
    op.drop_index(op.f('ix_KBNeo4jConnection_tenant_id'), table_name='KBNeo4jConnection')
    op.drop_index(op.f('ix_KBNeo4jConnection_created_at'), table_name='KBNeo4jConnection')
    op.drop_index('idx_kbneo4jconnection_inserted_at_desc', table_name='KBNeo4jConnection')
    op.drop_index('idx_kbneo4jconn_tenant_connected', table_name='KBNeo4jConnection', postgresql_where=sa.text('is_connected = true'))
    op.drop_table('KBNeo4jConnection')
    op.drop_index(op.f('ix_KBFilterPolicy_tenant_id'), table_name='KBFilterPolicy')
    op.drop_index(op.f('ix_KBFilterPolicy_created_at'), table_name='KBFilterPolicy')
    op.drop_index('idx_kbfilterpolicy_tenant_lang', table_name='KBFilterPolicy')
    op.drop_index('idx_kbfilterpolicy_inserted_at_desc', table_name='KBFilterPolicy')
    op.drop_table('KBFilterPolicy')
    op.drop_index(op.f('ix_KBExtractionPolicy_tenant_id'), table_name='KBExtractionPolicy')
    op.drop_index(op.f('ix_KBExtractionPolicy_created_at'), table_name='KBExtractionPolicy')
    op.drop_index('idx_kbextractionpolicy_tenant_lang', table_name='KBExtractionPolicy')
    op.drop_index('idx_kbextractionpolicy_inserted_at_desc', table_name='KBExtractionPolicy')
    op.drop_table('KBExtractionPolicy')
    op.drop_index(op.f('ix_KBData_tenant_id'), table_name='KBData')
    op.drop_index(op.f('ix_KBData_created_at'), table_name='KBData')
    op.drop_index('idx_kbdata_tenant_tier', table_name='KBData')
    op.drop_index('idx_kbdata_tenant_source', table_name='KBData')
    op.drop_index('idx_kbdata_tenant_role', table_name='KBData')
    op.drop_index('idx_kbdata_inserted_at_desc', table_name='KBData')
    op.drop_table('KBData')
    op.drop_index(op.f('ix_KBConnections_tenant_id'), table_name='KBConnections')
    op.drop_index('idx_kbconnections_tenant', table_name='KBConnections')
    op.drop_index('idx_kbconnections_inserted_at_desc', table_name='KBConnections')
    op.drop_table('KBConnections')
    op.drop_index(op.f('ix_KBConflictBatch_tenant_id'), table_name='KBConflictBatch')
    op.drop_index(op.f('ix_KBConflictBatch_created_at'), table_name='KBConflictBatch')
    op.drop_index('idx_kbconflictbatch_inserted_at_desc', table_name='KBConflictBatch')
    op.drop_table('KBConflictBatch')
    op.drop_index(op.f('ix_IPAllowlists_tenant_id'), table_name='IPAllowlists')
    op.drop_index('idx_ip_allowlists_tenant', table_name='IPAllowlists')
    op.drop_index('idx_ip_allowlists_inserted_at_desc', table_name='IPAllowlists')
    op.drop_table('IPAllowlists')
    op.drop_index(op.f('ix_AuditLogs_created_at'), table_name='AuditLogs')
    op.drop_index('idx_audit_logs_tenant', table_name='AuditLogs')
    op.drop_index('idx_audit_logs_source_event', table_name='AuditLogs', postgresql_where=sa.text('source_event_id IS NOT NULL'))
    op.drop_index('idx_audit_logs_inserted_at_desc', table_name='AuditLogs')
    op.drop_table('AuditLogs')
    op.drop_index(op.f('ix_Agents_tenant_id'), table_name='Agents')
    op.drop_index('idx_agents_tenant', table_name='Agents')
    op.drop_index('idx_agents_inserted_at_desc', table_name='Agents')
    op.drop_table('Agents')
    op.drop_index(op.f('ix_APIKeys_tenant_id'), table_name='APIKeys')
    op.drop_index('idx_api_keys_tenant', table_name='APIKeys')
    op.drop_index('idx_api_keys_key_hash', table_name='APIKeys')
    op.drop_index('idx_api_keys_inserted_at_desc', table_name='APIKeys')
    op.drop_table('APIKeys')
    op.drop_index(op.f('ix_Tenants_plan_id'), table_name='Tenants')
    op.drop_index(op.f('ix_Tenants_created_at'), table_name='Tenants')
    op.drop_index('idx_tenants_slug', table_name='Tenants')
    op.drop_index('idx_tenants_inserted_at_desc', table_name='Tenants')
    op.drop_table('Tenants')
    op.drop_index(op.f('ix_RollbackOperations_pipeline_id'), table_name='RollbackOperations')
    op.drop_index('idx_rollback_ops_inserted_at_desc', table_name='RollbackOperations')
    op.drop_index('idx_rollback_ops_env', table_name='RollbackOperations')
    op.drop_table('RollbackOperations')
    op.drop_index(op.f('ix_ReleasePackages_pipeline_id'), table_name='ReleasePackages')
    op.drop_index('idx_release_packages_status', table_name='ReleasePackages')
    op.drop_index('idx_release_packages_inserted_at_desc', table_name='ReleasePackages')
    op.drop_table('ReleasePackages')
    op.drop_index(op.f('ix_PipelineSteps_pipeline_id'), table_name='PipelineSteps')
    op.drop_index('idx_pipeline_steps_pipeline', table_name='PipelineSteps')
    op.drop_index('idx_pipeline_steps_inserted_at_desc', table_name='PipelineSteps')
    op.drop_table('PipelineSteps')
    op.drop_index(op.f('ix_KBWarehouseConfig_warehouse_id'), table_name='KBWarehouseConfig')
    op.drop_index(op.f('ix_KBWarehouseConfig_created_at'), table_name='KBWarehouseConfig')
    op.drop_index('idx_kbwarehouseconfig_wh_version', table_name='KBWarehouseConfig')
    op.drop_index('idx_kbwarehouseconfig_wh_active', table_name='KBWarehouseConfig', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_kbwarehouseconfig_inserted_at_desc', table_name='KBWarehouseConfig')
    op.drop_table('KBWarehouseConfig')
    op.drop_index(op.f('ix_KBModelVersion_created_at'), table_name='KBModelVersion')
    op.drop_index('idx_kbmodelversion_model_version', table_name='KBModelVersion', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_kbmodelversion_inserted_at_desc', table_name='KBModelVersion')
    op.drop_table('KBModelVersion')
    op.drop_index('idx_guardrails_inserted_at_desc', table_name='Guardrails')
    op.drop_table('Guardrails')
    op.drop_index('idx_role_permissions_role', table_name='RolePermissions')
    op.drop_index('idx_role_permissions_inserted_at_desc', table_name='RolePermissions')
    op.drop_table('RolePermissions')
    op.drop_table('Plans')
    op.drop_index('idx_pipelines_status', table_name='Pipelines')
    op.drop_index('idx_pipelines_inserted_at_desc', table_name='Pipelines')
    op.drop_table('Pipelines')
    op.drop_index('idx_llmproviders_type_is_default', table_name='LLMProviders', postgresql_where=sa.text('is_default = true'))
    op.drop_index('idx_llmproviders_inserted_at_desc', table_name='LLMProviders')
    op.drop_table('LLMProviders')
    op.drop_index(op.f('ix_KBWarehouse_created_at'), table_name='KBWarehouse')
    op.drop_index('idx_kbwarehouse_inserted_at_desc', table_name='KBWarehouse')
    op.drop_table('KBWarehouse')
    op.drop_index(op.f('ix_KBModel_task_type'), table_name='KBModel')
    op.drop_index(op.f('ix_KBModel_created_at'), table_name='KBModel')
    op.drop_index('idx_kbmodel_inserted_at_desc', table_name='KBModel')
    op.drop_table('KBModel')
    op.drop_index(op.f('ix_KBEntityLookup_created_at'), table_name='KBEntityLookup')
    op.drop_index(op.f('ix_KBEntityLookup_canonical_name'), table_name='KBEntityLookup')
    op.drop_index('idx_kbentitylookup_inserted_at_desc', table_name='KBEntityLookup')
    op.drop_index('idx_kbentitylookup_alias', table_name='KBEntityLookup', postgresql_using='hash')
    op.drop_table('KBEntityLookup')
    op.drop_index('idx_env_configs_inserted_at_desc', table_name='EnvironmentConfigs')
    op.drop_index('idx_env_configs_env', table_name='EnvironmentConfigs')
    op.drop_table('EnvironmentConfigs')
    op.drop_index('idx_drift_events_resolved', table_name='DriftEvents')
    op.drop_index('idx_drift_events_inserted_at_desc', table_name='DriftEvents')
    op.drop_table('DriftEvents')
    # ### end Alembic commands ###
