CREATE DATABASE litellm;
GRANT ALL PRIVILEGES ON DATABASE litellm TO admin;
CREATE DATABASE langfuse;
GRANT ALL PRIVILEGES ON DATABASE langfuse TO admin;
CREATE DATABASE knowledge_base;
GRANT ALL PRIVILEGES ON DATABASE knowledge_base TO admin;
